application: ayastudymg
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /font
  static_dir: font

- url: /js
  static_dir: js

- url: /stylesheets
  static_dir: stylesheets

- url: /img
  static_dir: img

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
